Jenkinsfile updated

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -3,14 +3,15 @@ pipeline {
 
     stages {
 
-        stage('Clone') {
+        stage('Checkout') {
             steps {
                 git branch: 'main',
-                url: 'git@github.com:Nagaraj991655/Air-Quality-Trends-Analysis-Project.git'
+                    credentialsId: 'github-ssh',
+                    url: 'git@github.com:Nagaraj991655/Air-Quality-Trends-Analysis-Project.git'
             }
         }
 
-        stage('Build') {
+        stage('Build Docker Images') {
             steps {
                 sh 'docker compose build'
             }
@@ -18,9 +19,30 @@ pipeline {
 
         stage('Deploy') {
             steps {
-                sh 'docker compose down'
+                sh 'docker compose down || true'
                 sh 'docker compose up -d'
             }
+        }
+
+        stage('Verify Containers') {
+            steps {
+                sh 'docker ps'
+            }
+        }
+    }
+
+    post {
+
+        success {
+            echo 'Deployment Successful!'
+        }
+
+        failure {
+            echo 'Deployment Failed!'
+        }
+
+        always {
+            sh 'docker ps -a || true'
         }
     }
 }
